version: '3.9'

services:
  currencyexchange.api:
    image: ${DOCKER_REGISTRY-}currencyexchangeapi
    container_name: CurrencyExchange.Api
    build:
      context: .
      dockerfile: CurrencyExchange.Api/Dockerfile
    depends_on: 
    - currencyexchange.db

  currencyexchange.db:
     image: postgres:latest
     container_name: CurrencyExchange.Db
     environment:
     - POSTGRES_DB=exchange
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     volumes:
      - ./.containers/database:/var/lib/postgresql/data
     ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  currencyexchange.redis:
    image: redis:latest
    container_name: CurrencyExchange.Redis
    restart: always
    ports:
      - '6379:6379'